### ISSUE TITLE
no template named 'WithDlgLayout' in namespace 'Upp' in GUI tutorial Gui16

### ISSUE THREAD

**Issue by erusyd** [ultimatepp/ultimatepp#73]
In GUI Tutorial, section “16.2 Upp namespace agnostic implementation”, the given code compiles with following error:

**error: no template named 'WithDlgLayout' in namespace 'Upp'; did you mean simply 'WithDlgLayout'?**

I need to remove the "Upp::" before "WithDlgLayout" to:
```
struct MyAppWindow : public WithDlgLayout<Upp::TopWindow> {
    MyAppWindow() {
        CtrlLayout(*this, "MyDialog");
    }
};
```

And, it seems that, by default, Layout Designer does not add "Upp::" before "InsetFrame()" in SetFrame(). I need to manually add "Upp::" before "InsetFrame()" in **dlg.lay** from:
```
LAYOUT(DlgLayout, 208, 64)
	ITEM(Upp::Label, dv___0, SetLabel(t_("Label")).LeftPosZ(8, 40).TopPosZ(8, 19))
	ITEM(Upp::EditString, text, SetFrame(InsetFrame()).LeftPosZ(48, 92).TopPosZ(8, 19))
	ITEM(Upp::Option, option, SetLabel(t_("Option")).LeftPosZ(8, 112).TopPosZ(36, 16))
END_LAYOUT
```
to
```
LAYOUT(DlgLayout, 208, 64)
	ITEM(Upp::Label, dv___0, SetLabel(t_("Label")).LeftPosZ(8, 40).TopPosZ(8, 19))
	ITEM(Upp::EditString, text, SetFrame(Upp::InsetFrame()).LeftPosZ(48, 92).TopPosZ(8, 19))
	ITEM(Upp::Option, option, SetLabel(t_("Option")).LeftPosZ(8, 112).TopPosZ(36, 16))
END_LAYOUT
```

**Comment by klugier** [comment]
Hello @erusyd,

Thank you for your report! Should be fixed in https://github.com/ultimatepp/ultimatepp/commit/d670725115b0f98d874bc7b886e1003958bbb376. Please verify GUI tutorial page tomorrow on our website (it is updated once per day).

Also, to tutorial dictionary. I had created Gui16a & Gui16b. The second one is Upp namespace agnostic implementation. The nightly build that contains this change will be available tomorrow, too.

I am closing this ticket now, if something will be wrong, please reopen.

Klugier

**Comment by mirek-fidler** [comment]
I think this does not solve Upp::InsetFrame() issue. That needs some work...

**Comment by erusyd** [comment]
> I think this does not solve Upp::InsetFrame() issue. That needs some work...

Yes. Anyway, U++ is a great software framework. Thank you guys!

**Comment by mirek-fidler** [comment]
I believe it should be finally solved in current master.

**Comment by klugier** [comment]
I can confirm that both cases has been fixed. @erusyd you could verify this by downloading latest nightly builds from  https://www.ultimatepp.org/www$uppweb$download$en-us.html.

**Comment by erusyd** [comment]
Verified. Thanks!

**Comment by FoxesChooseJiff** [comment]
This still appears to be an issue with stable build no. 16847. Searching `WithDlgLayout` on here yields results for the tutorial files, but the template class is nowhere to be found. Could it be missing?
